[package]
name = "sirun"
version = "0.1.0"
authors = ["Bryan English <bryan.english@datadoghq.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
async-std = { version = "1.9.0", features = ["unstable", "attributes"] }
serde_json = "1.0.64"
shlex = "1.0.0"
nix = "0.20.0"
