name: CI

on: 
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install valgrind
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install valgrind
          fi
      - name: Tests
        run: cargo test
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets
