on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        id: octo-sts
        with:
          scope: DataDog/sirun
          policy: self.release.create-release
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin
            os: macos-latest-large
          - target: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os || 'ubuntu-latest'}}
    permissions:
      id-token: write
    steps:
      - uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        id: octo-sts
        with:
          scope: DataDog/sirun
          policy: self.release.create-release
      - uses: actions/checkout@v2
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: sirun
          target: ${{ matrix.target }}
          archive: $bin-$tag-$target
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
          CARGO_PROFILE_RELEASE_LTO: true
